# Generated by Django 4.0.1 on 2024-07-09 12:20

import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.ReaderManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'Author'), (2, 'Editor'), (3, 'Moderator'), (4, 'Admin'), (5, 'Reader')], default=5, max_length=25),
        ),
    ]
