# Generated by Django 4.0.1 on 2024-07-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reader_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Author'), (2, 'Editor'), (3, 'Moderator'), (4, 'Admin'), (5, 'Reader')], default=5, max_length=25),
        ),
    ]
