# Generated by Django 4.0.1 on 2025-06-11 04:57

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_delete_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.WriterManager()),
            ],
        ),
    ]
