services:
  db:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: crowpro
      MYSQL_USER: mysqluser
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldb:/var/lib/crowpro/data

  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - /usr/src/
    command:
      python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

volumes:
  mysqldb: