databases:
  - name: crowcrows
    plan: free
    databaseName: crowcrows
    user: crowcrows

services:
  - type: web
    plan: free
    name: crowcrows
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: postgresql://crowcrows:mJZoV3Lvt2Z89cuAHyxtEvGmphOuizhN@dpg-csve96ij1k6c73c4tn50-a/crowcrows
        fromDatabase:
          name: crowcrows
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4