# Generated by Django 4.0.1 on 2024-09-06 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editorial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
