# Generated by Django 4.0.1 on 2025-04-03 08:48

import blog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
        ('blog', '0005_alter_editorial_published_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.TextField(default='ARTICLE', verbose_name=blog.models.Publication.PublicationType)),
                ('title', models.CharField(default='', max_length=128)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('hide', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_by', to='users.editor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='users.author')),
            ],
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.publication',),
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.publication',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
