# Generated by Django 4.0.1 on 2025-04-10 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_delete_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_publication_remove_editorial_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(related_name='publications', through='blog.PublicationAuthor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.TextField(choices=[('EDITORIAL', 'Editorial'), ('ARTICLE', 'Article')], default='ARTICLE'),
        ),
        migrations.AddField(
            model_name='publicationauthor',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.publication'),
        ),
        migrations.AddField(
            model_name='publicationauthor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
