# Generated by Django 4.0.1 on 2025-06-11 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_writer'),
        ('blog', '0009_alter_publication_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(related_name='publications', through='blog.PublicationAuthor', to='users.Writer'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='users.writer'),
        ),
        migrations.AlterField(
            model_name='publicationauthor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.writer'),
        ),
    ]
