# Generated by Django 4.0.1 on 2025-06-11 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_publication_authors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.publication')),
            ],
        ),
    ]
