# Generated by Django 5.2.6 on 2025-09-21 21:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_publicationseries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationseries',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='publicationseries',
            name='publication',
        ),
        migrations.AddField(
            model_name='publicationseries',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicationseries',
            name='updated_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PublicationSeriesChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.publication')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.publicationseries')),
            ],
        ),
    ]
