# Generated by Django 4.0.1 on 2024-09-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_editorial_hide_editorial_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
